package store

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5/pgconn"
)

func TestCanonicalRecoveryJSONMatchesFrozenTypeScriptEscapes(t *testing.T) {
	// Given values and SHA-256 bytes generated by the frozen TypeScript producer
	// (canonicalRecoveryJson) under Node v24.14.0.
	backslash := "\\"
	actual2028 := "\u2028"
	actual2029 := "\u2029"
	tests := []struct {
		name     string
		value    any
		wantHex  string
		wantHash string
	}{
		{
			name:     "actual U+2028 and U+2029",
			value:    "actual" + actual2028 + "middle" + actual2029 + "end",
			wantHex:  "2261637475616ce280a86d6964646c65e280a9656e6422",
			wantHash: "c520f2cb5449f51e98bc4e2544ff5212945caa361a1072fdcfd9e436889eb86e",
		},
		{
			name:     "literal U+2028 and U+2029 escape text",
			value:    "literal" + backslash + "u2028-middle" + backslash + "u2029-end",
			wantHex:  "226c69746572616c5c5c75323032382d6d6964646c655c5c75323032392d656e6422",
			wantHash: "f791e97e5898c26c8c16342f3d8ce9d4cdfedf5fd70698fa7012d44051c20a12",
		},
		{
			name:     "adjacent and doubled backslashes",
			value:    "adjacent" + backslash + "u2028" + backslash + "u2029doubled" + backslash + backslash + "u2028actual" + actual2028 + actual2029,
			wantHex:  "2261646a6163656e745c5c75323032385c5c7532303239646f75626c65645c5c5c5c753230323861637475616ce280a8e280a922",
			wantHash: "b1a8d685003eed017df736288badf9d0c67dca4a2df54c5e959a57b8d696dacb",
		},
		{
			name:     "HTML punctuation and ordinary Unicode",
			value:    "<>& 한글 😀 café",
			wantHex:  "223c3e2620ed959ceab88020f09f988020636166c3a922",
			wantHash: "89773c901a81968e71e07feb44dd34de58d2c86d3302dad3ce3ed3c3b916d2e2",
		},
		{
			name: "null version in nested map and array",
			value: map[string]any{"sourceSpec": map[string]any{
				"version":     nil,
				"desiredSpec": map[string]any{"z": "last", "a": []any{nil, "", backslash + "u2028", actual2029}},
			}},
			wantHex:  "7b22736f7572636553706563223a7b226465736972656453706563223a7b2261223a5b6e756c6c2c22222c225c5c7532303238222c22e280a9225d2c227a223a226c617374227d2c2276657273696f6e223a6e756c6c7d7d",
			wantHash: "ab92e5d52b7df78fc66adb4474c21f3be7319f1bb0addac3cbc04b7018c186a3",
		},
		{
			name: "empty version in nested map and array",
			value: map[string]any{"sourceSpec": map[string]any{
				"version":     "",
				"desiredSpec": map[string]any{"z": "last", "a": []any{nil, "", backslash + "u2028", actual2029}},
			}},
			wantHex:  "7b22736f7572636553706563223a7b226465736972656453706563223a7b2261223a5b6e756c6c2c22222c225c5c7532303238222c22e280a9225d2c227a223a226c617374227d2c2276657273696f6e223a22227d7d",
			wantHash: "9ed3691ad1ad51a64d8af28895d35089d72a140fa5dbd31ab3d37163e86c2dfa",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// When Go canonicalizes the same JSON value.
			raw, err := json.Marshal(tt.value)
			if err != nil {
				t.Fatal(err)
			}
			got, err := canonicalRecoveryJSON(raw)

			// Then its bytes remain valid JSON and match the TypeScript producer.
			if err != nil {
				t.Fatal(err)
			}
			if !json.Valid(got) {
				t.Fatalf("invalid canonical JSON: %x", got)
			}
			if gotHex := hex.EncodeToString(got); gotHex != tt.wantHex {
				t.Fatalf("canonical bytes=%s want=%s", gotHex, tt.wantHex)
			}
			sum := sha256.Sum256(got)
			if gotHash := hex.EncodeToString(sum[:]); gotHash != tt.wantHash {
				t.Fatalf("canonical SHA-256=%s want=%s", gotHash, tt.wantHash)
			}
		})
	}
}

func TestRecoverySourceGenerationMatchesFrozenTypeScript(t *testing.T) {
	// Given the cross-language fixture evaluated by the frozen TypeScript producer.
	r := &Resource{
		ID: "source", ProjectID: "project", Type: "database", Engine: "postgresql", Provider: "raibitserver", Plan: "shared-small", Region: "local", ConnectionSecretName: "db-connection",
		DesiredSpec: map[string]any{"databaseName": "name<>&", "storageGb": 1}, DesiredState: decodeMap([]byte(recoveryState())),
	}
	// When Go recomputes the incarnation before a side effect.
	got, err := recoverySourceGeneration(r)
	// Then bytes match the independently executed producer, not a Go-derived expectation.
	const expected = "resource-incarnation/v1:sha256:b2313a70a0549dafdc7d8b8fb309f60b0d4658865cc89e24e1bc32ad85854571"
	if err != nil || got != expected {
		t.Fatalf("canonical hash=%s err=%v", got, err)
	}
}

func TestRecoverySourceGenerationIgnoresOnlyObservationTime(t *testing.T) {
	// Given identical immutable provenance with a later successful health observation.
	r := &Resource{ID: "source", ProjectID: "project", Type: "database", Engine: "postgresql", Provider: "raibitserver", Plan: "shared-small", Region: "local", ConnectionSecretName: "db-connection", DesiredState: decodeMap([]byte(recoveryState()))}
	before, err := recoverySourceGeneration(r)
	if err != nil {
		t.Fatal(err)
	}
	r.DesiredState = decodeMap([]byte(strings.Replace(recoveryState(), "2026-09-03", "2026-09-04", 1)))
	// When observation time changes without resource replacement.
	after, err := recoverySourceGeneration(r)
	// Then the incarnation remains stable.
	if err != nil || before != after {
		t.Fatal("health timestamp changed source incarnation")
	}
}

func TestRecoverySourceGenerationDistinguishesNullAndEmptyVersion(t *testing.T) {
	// Given nullable and explicitly empty version values, which the producer hashes differently.
	r := &Resource{ID: "source", ProjectID: "project", Type: "database", Engine: "postgresql", Provider: "raibitserver", Plan: "shared-small", Region: "local", ConnectionSecretName: "db-connection", DesiredState: decodeMap([]byte(recoveryState()))}
	absent, err := recoverySourceGeneration(r)
	if err != nil {
		t.Fatal(err)
	}
	r.VersionPresent = true
	// When the SQL NULL distinction is preserved.
	empty, err := recoverySourceGeneration(r)
	// Then nullable provenance cannot alias an explicit empty version.
	if err != nil || absent == empty {
		t.Fatal("SQL nullable version aliased empty string")
	}
}

func TestRecoverySourceGenerationRejectsAbsentOrForgedImage(t *testing.T) {
	for _, image := range []string{"{}", strings.Replace(recoveryState(), strings.Repeat("1", 64), strings.Repeat("0", 64), 1), strings.Replace(recoveryState(), `"workloadGeneration":1`, `"workloadGeneration":0`, 1)} {
		// Given missing or invalid applied-image evidence.
		r := &Resource{DesiredState: decodeMap([]byte(image))}
		// When a recovery fence needs the incarnation.
		_, err := recoverySourceGeneration(r)
		// Then configuration/zero evidence cannot substitute for observed image provenance.
		if err == nil {
			t.Fatal("unproven source accepted")
		}
	}
}

func TestRecoveryStorageErrorNeverContainsBackendDetail(t *testing.T) {
	// Given a PostgreSQL error carrying private object identity and credentials in its body.
	raw := &pgconn.PgError{Code: "42804", Message: "secret=credential", Detail: "organizations/private/artifact"}
	// When the store reports the failure.
	err := recoveryDBFailure(raw)
	// Then only the stable SQLSTATE is exposed.
	if err.Error() != "RECOVERY_STORAGE_FAILURE:42804" {
		t.Fatalf("unsafe error %q", err.Error())
	}
}
