{{- if .Values.provisioner.backups.enabled }}
{{- if not (trim .Values.provisioner.backups.endpoint) }}
{{- fail "enabled provisioner backup endpoint is required" }}
{{- end }}
{{- if not (trim .Values.provisioner.backups.bucket) }}
{{- fail "enabled provisioner backup bucket is required" }}
{{- end }}
{{- if not (trim .Values.provisioner.backups.existingSecret) }}
{{- fail "enabled provisioner backup existing Secret is required" }}
{{- end }}
{{- if not (trim .Values.provisioner.backups.secretKey) }}
{{- fail "enabled provisioner backup Secret data key is required" }}
{{- end }}
{{- end }}
